Lecture 5 homework
Letto228/Angular-learnjs-030723 pull request #42
Opened 2023-07-28 10:11 UTC by Qusz

2023-08-01 07:18 UTC, Letto228 reviewed
Привет!
Классный МР 👍. Есть один вопрос - оставил комментарий. Буду ждать фидбека!

2023-08-01 07:18 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +        const nearBottom =
А есть ли смысл отслеживать направление скролла? Например, что скроллим вниз и пересекаем нижнюю границу, а не верхнюю (когда будем скроллит вниз с самого верха, будет ли эмититься событие загрузки сверху)?

2023-08-01 15:10 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +        const borderOffset = 100;
Почему не стал выделять в константу на уровне фичи?

2023-08-01 15:11 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +    onScroll(target: HTMLElement): void {
Я бы предложил воспользоваться деструктуризацией, что думаешь? `scrollChange({scrollHeight, scrollTop}: HTMLElement) {`

2023-08-05 13:12 UTC, Qusz commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +        const nearBottom =
Пофиксил

2023-08-05 13:14 UTC, Qusz commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +        const borderOffset = 100;
пофискил

2023-08-05 13:14 UTC, Qusz commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +    onScroll(target: HTMLElement): void {
Сделал

2023-08-13 14:37 UTC, Letto228 requested changes
Привет!
В целом все гуд 👍, но пару практик показались мне сомнительными - оставил комментарии, посмотри, пожалуйста. Буду очень ждать твоег офидбека!

2023-08-13 14:37 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +    private scrollDirection: 'up' | 'down' | undefined;
Тут стоило бы воспользоваться не строковыми типами, а существующим `enum` `LoadDirection`. А вообще, нужно ли нам хранить в отдельном свойстве `scrollDirection`? Мне кажется, что мы его вычислили для функции `onScroll`, выполнили сравнение и все, дальше в свойстве нет необходимости.

2023-08-13 14:37 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +        switch (true) {
Выглядит как костыль 🩼. Почему использовал подобную практику?

Мне кажется было бы намного прозрачней использовать несколько блоков if + ранний ретерн.

2023-08-13 14:37 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +    private getScrollDirection(currentScrollPosition: number) {
Как раз эта функция бы могла вернуть `LoadDirection` и в `onScroll`, при помощи полученного значения, мы бы сделали необходимые вычисления. И в функции тогда бы могли использовать красивый тернарник, а не `else if` - `return currentScrollPosition > this.scrollPosition ? LoadDirection.Down : LoadDirection.Up`.

2023-08-13 14:37 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +        this.scrollPosition = currentScrollPosition;
Выглядит как неочевидный side effect, т.к. не ожидается, что при выполнении функции `getScrollDirection` будет обновлен `scrollPosition`. Я бы вынес данное действие в основной поток функции `onScroll`, там логически это ничему не противоречит и будет выглядеть прозрачно.

2023-08-13 14:37 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +    private scrollDirection: 'up' | 'down' | undefined;
В коде мы смотрим на строковые типы, но эмитим `LoadDirection` в output. Давай везде просто работать с `LoadDirection`? Ведь так и проще работать и прозрачней логика будет

2024-01-21 10:44 UTC, closed without merging